---
title: "Fundacion Juan March - Visitors"
author: "Diego Enriquez"
date: "4/10/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, warning=FALSE}
suppressMessages(library(data.table))
suppressMessages(library(lubridate))
suppressMessages(library(ggplot2))
suppressMessages(library(grid))

# Functions ==================================================================================================================================
source("fjm_func.R")
```

## Fundacion Juan March visitors by year

```{r echo=FALSE, warning=FALSE}
fjm_visitors <- readVisitorData()
fjm_visitors <- fjm_visitors[Date >= "2016-01-01"]
fjm_visitors[is.na(visitors)]$visitors = 0

daysinfo <- data.table(Date = seq(as.Date("2016-01-01"), as.Date("2018-06-24"), by = "day"))
daysinfo$weekNum <- wday(daysinfo$Date, week_start = 1)
daysinfo$monthNum <- mday(daysinfo$Date)
daysinfo$isFirstSunday <- wday(daysinfo$Date, week_start = 1) == 7 & day(daysinfo$Date) <= 7
```

```{r echo=FALSE, fig.width=10}
ggplot(fjm_visitors, aes(Date, visitors)) +
  geom_vline(xintercept = daysinfo[monthNum == 1, Date], col = "lightblue", lty = 2) +
  geom_line(stat = "identity", size = 0.25) +
  theme_bw()
```

#### 2016

```{r echo=FALSE, fig.width=10}
ggplot(fjm_visitors, aes(Date, visitors)) +
  geom_vline(xintercept = daysinfo[monthNum == 1, Date], col = "lightblue", lty = 2) +
  geom_line(stat = "identity", size = 0.25) +
  theme_bw() +
  coord_cartesian(xlim = as.Date(c("2016-01-01", "2016-12-31")), ylim = c(0, 1700))
```

#### 2017

```{r echo=FALSE, fig.width=10}
ggplot(fjm_visitors, aes(Date, visitors)) +
  geom_vline(xintercept = daysinfo[monthNum == 1, Date], col = "lightblue", lty = 2) +
  geom_line(stat = "identity", size = 0.25) +
  theme_bw() +
  coord_cartesian(xlim = as.Date(c("2017-01-01", "2017-12-31")), ylim = c(0, 2200))
```

#### 2018

```{r echo=FALSE, fig.width=10}
ggplot(fjm_visitors, aes(Date, visitors)) +
  geom_vline(xintercept = daysinfo[monthNum == 1, Date], col = "lightblue", lty = 2) +
  geom_line(stat = "identity", size = 0.25) +
  theme_bw() +
  coord_cartesian(xlim = as.Date(c("2018-01-01", "2018-12-31")), ylim = c(0, 4900))
```

## Showing moving average

```{r echo=FALSE, fig.width=10}
ggplot(fjm_visitors, aes(Date, visitors)) +
  geom_vline(xintercept = daysinfo[monthNum == 1, Date], col = "lightblue", lty = 2) +
  geom_line(stat = "identity", size = 0.25) +
  geom_line(data = movingAverage(fjm_visitors), aes(Date, visitors), size = 0.5, col = "blue") +
  theme_bw()
```

#### 2016

```{r echo=FALSE, fig.width=10}
ggplot(fjm_visitors, aes(Date, visitors)) +
  geom_vline(xintercept = daysinfo[monthNum == 1, Date], col = "lightblue", lty = 2) +
  geom_line(stat = "identity", size = 0.25) +
  geom_line(data = movingAverage(fjm_visitors), aes(Date, visitors), size = 0.5, col = "blue") +
  theme_bw() +
  coord_cartesian(xlim = as.Date(c("2016-01-01", "2016-12-31")), ylim = c(0, 1700))
```

#### 2017

```{r echo=FALSE, fig.width=10}
ggplot(fjm_visitors, aes(Date, visitors)) +
  geom_vline(xintercept = daysinfo[monthNum == 1, Date], col = "lightblue", lty = 2) +
  geom_line(stat = "identity", size = 0.25) +
  geom_line(data = movingAverage(fjm_visitors), aes(Date, visitors), size = 0.5, col = "blue") +
  theme_bw() +
  coord_cartesian(xlim = as.Date(c("2017-01-01", "2017-12-31")), ylim = c(0, 2200))
```

#### 2018

```{r echo=FALSE, fig.width=10}
ggplot(fjm_visitors, aes(Date, visitors)) +
  geom_vline(xintercept = daysinfo[monthNum == 1, Date], col = "lightblue", lty = 2) +
  geom_line(stat = "identity", size = 0.25) +
  geom_line(data = movingAverage(fjm_visitors), aes(Date, visitors), size = 0.5, col = "blue") +
  theme_bw() +
  coord_cartesian(xlim = as.Date(c("2018-01-01", "2018-12-31")), ylim = c(0, 4900))
```

## Showing trend

```{r echo=FALSE, fig.width=10}
ggplot(fjm_visitors, aes(Date, visitors)) +
  geom_vline(xintercept = daysinfo[monthNum == 1, Date], col = "lightblue", lty = 2) +
  geom_line(stat = "identity", size = 0.25) +
  geom_line(data = trendValues(fjm_visitors), aes(Date, visitors), size = 0.5, col = "blue") +
  theme_bw()
```

#### 2016

```{r echo=FALSE, fig.width=10}
ggplot(fjm_visitors, aes(Date, visitors)) +
  geom_vline(xintercept = daysinfo[monthNum == 1, Date], col = "lightblue", lty = 2) +
  geom_line(stat = "identity", size = 0.25) +
  geom_line(data = trendValues(fjm_visitors), aes(Date, visitors), size = 0.5, col = "blue") +
  theme_bw() +
  coord_cartesian(xlim = as.Date(c("2016-01-01", "2016-12-31")), ylim = c(0, 1700))
```

#### 2017

```{r echo=FALSE, fig.width=10}
ggplot(fjm_visitors, aes(Date, visitors)) +
  geom_vline(xintercept = daysinfo[monthNum == 1, Date], col = "lightblue", lty = 2) +
  geom_line(stat = "identity", size = 0.25) +
  geom_line(data = trendValues(fjm_visitors), aes(Date, visitors), size = 0.5, col = "blue") +
  theme_bw() +
  coord_cartesian(xlim = as.Date(c("2017-01-01", "2017-12-31")), ylim = c(0, 2200))
```

#### 2018

```{r echo=FALSE, fig.width=10}
ggplot(fjm_visitors, aes(Date, visitors)) +
  geom_vline(xintercept = daysinfo[monthNum == 1, Date], col = "lightblue", lty = 2) +
  geom_line(stat = "identity", size = 0.25) +
  geom_line(data = movingAverage(fjm_visitors), aes(Date, visitors), size = 0.5, col = "blue") +
  theme_bw() +
  coord_cartesian(xlim = as.Date(c("2018-01-01", "2018-12-31")), ylim = c(0, 4900))
```

## Zooom to some weeks

#### Feb-Mar 2016
Blue lines represent Saturdays
```{r echo=FALSE, fig.width=10}
ggplot(fjm_visitors, aes(Date, visitors)) +
  geom_vline(xintercept = daysinfo[weekNum == 6, Date], col = "lightblue", lty = 2) +
  geom_line(stat = "identity", size = 0.25) +
  geom_line(data = trendValues(fjm_visitors), aes(Date, visitors), size = 0.5, col = "blue") +
  theme_bw() +
  coord_cartesian(xlim = as.Date(c("2016-02-01", "2016-03-31")), ylim = c(0, 1700))
```

#### Apr-May 2017
Blue lines represent Saturdays
```{r echo=FALSE, fig.width=10}
ggplot(fjm_visitors, aes(Date, visitors)) +
  geom_vline(xintercept = daysinfo[weekNum == 6, Date], col = "lightblue", lty = 2) +
  geom_line(stat = "identity", size = 0.25) +
  geom_line(data = trendValues(fjm_visitors), aes(Date, visitors), size = 0.5, col = "blue") +
  theme_bw() +
  coord_cartesian(xlim = as.Date(c("2017-04-01", "2017-05-31")), ylim = c(0, 1700))
```

#### Jan-Feb 2018
Blue lines represent Saturdays
```{r echo=FALSE, fig.width=10}
ggplot(fjm_visitors, aes(Date, visitors)) +
  geom_vline(xintercept = daysinfo[weekNum == 6, Date], col = "lightblue", lty = 2) +
  geom_line(stat = "identity", size = 0.25) +
  geom_line(data = trendValues(fjm_visitors), aes(Date, visitors), size = 0.5, col = "blue") +
  theme_bw() +
  coord_cartesian(xlim = as.Date(c("2018-01-01", "2018-02-28")), ylim = c(0, 4900))
```